version: "3.8"

services:
  web-app:
    build:
      context: ./web-app
    container_name: web-app
    ports:
      - "3000:3000"
    volumes:
      - recordings:/app/recordings
    environment:
      - MONGO_URI=mongodb+srv://nb3460:9paNoydyVz52hqhO@cluster0.zfwsq7e.mongodb.net/Speech2Text?retryWrites=true&w=majority&appName=Cluster0
      - MONGO_DBNAME=speech2text
    depends_on:
      - mongodb
    networks:
      - backend

  ml-client:
    build:
      context: ./machine-learning-client
    container_name: ml-client
    volumes:
      - recordings:/app/recordings
    environment:
      - MONGO_URI=mongodb+srv://nb3460:9paNoydyVz52hqhO@cluster0.zfwsq7e.mongodb.net/Speech2Text?retryWrites=true&w=majority&appName=Cluster0
      - MONGO_DBNAME=speech2text
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend

volumes:
  recordings:

networks:
  backend:
