version: "3.8"

services:
  web-app:
    build:
      context: ./web-app
    container_name: web-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_DBNAME=speech2text
    depends_on:
      - mongodb
      - client
    networks:
      - backend

  client:
    build:
      context: ./machine-learning-client
    container_name: ml-client
    environment:
      - MONGO_DBNAME=speech2text
    depends_on:
      - mongodb
    ports:
      - "5001:5001"
    networks:
      - backend

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend

volumes:
  recordings:

networks:
  backend: