name: Web App CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4

      - name: install dependencies
        run: |
          sudo apt-get install portaudio19-dev
          pip install pipenv
          pipenv install --dev
          pipenv install -r web-app/requirements.txt

      - name: run tests
        run: |
          pipenv install pytest
          pipenv run pytest web-app/src/test_app.py
