name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: install pyaudio dependency
        run: sudo apt-get update && sudo apt-get install -y portaudio19-dev

      - name: install dependencies
        run: |
          pipenv install --dev
          pipenv install -r machine-learning-client/requirements.txt

      - name: run tests
        run: pipenv install pytest
        # run: pipenv run pytest machine-learning-client/test_client.py
