name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    defaults:
      # run:
      #   working-directory: ./web-app
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      # - name: setup docker
      #   uses: docker/setup-buildx-action@v3
      - name: build app
        run: docker build -t web-app ./web-app
      - name: run app
        run: docker run --rm web-app
      - name: run tests
        run: docker exec -it web-app pytest
